# Generated by Django 4.2 on 2024-04-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
