# Generated by Django 4.2 on 2024-04-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosApp', '0002_remove_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
